include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Dart style
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_locals: true
    avoid_print: true
    use_key_in_widget_constructors: true
    # Disabled rules
    avoid_unnecessary_containers: false

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - lib/generated/**
